
// This file was auto-generated by ML.NET Model Builder. 

using AnimalClassification_ConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"D:\animals_training\antelope\02f4b3be2d.jpg");
AnimalClassification.ModelInput sampleData = new AnimalClassification.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = AnimalClassification.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
